version: '3.8'

services:
  mysql:
    image: mariadb:latest  # Corregido de 'lastest' a 'latest'
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - test-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminbackend
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: test
      PMA_PASSWORD: test
    ports:
      - "8080:80"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge  # Opcional: especifica el driver de red


# version: "3.8"
# services:
#   postgresDB:
#     image: postgres:14.1-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=vsemprendedor2
#     volumes:
#       - ./postgres:/var/lib/postgresql/data
#     ports:
#       - "5436:5432"

#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     ports:
#       - "5050:80"
#     depends_on:
#       - postgresDB
#     environment:
#       PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
#       PGADMIN_DEFAULT_PASSWORD: "postgres"

